{% set name = "pengwann" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pengwann-{{ version }}.tar.gz
  sha256: 33c47439a4c4d9106f882d6b9037f9c808f6e79923240d14b88f7ea5cd5e58ba

build:
  number: 0
  skip: true  # [py<310]
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - cd rust
    - cargo-bundle-licenses --format yaml --output ../THIRDPARTY.yml

requirements:
  build:
    - python  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - maturin >=1.0,<2.0  # [build_platform != target_platform]
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.0,<2.0
    - pip
  run:
    - python
    - numpy >=2
    - scipy
    - tqdm
    - typing_extensions >=4.12,<5.0

test:
  imports:
    - pengwann
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/PatrickJTaylor/pengWann
  dev_url: https://github.com/PatrickJTaylor/pengWann
  doc_url: https://pengwann.readthedocs.io
  summary: Computation of chemical bonding descriptors from Wannier functions
  description: |
    A lightweight Python package for calculating descriptors of chemical bonding and
    local electronic structure from Wannier functions.
  license: GPL-3.0-or-later
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - PatrickJTaylor
