github:
  branch_name: main
  tooling_branch_name: main
build_platform:
  linux_32: linux_64
  linux_aarch64: linux_64
  linux_armv7l: linux_64
  linux_ppc64le: linux_64
  linux_s390x: linux_64
  osx_arm64: osx_64
  win_32: win_64
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
